import type { Metadata } from "next";
import NextjsToploader from "nextjs-toploader";
import "./globals.css";
import { QueryProvider } from "@/providers/queryProvider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased" suppressHydrationWarning={true}>
        <NextjsToploader color="#09C791" showSpinner={false} height={3} />
        <Toaster />
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
